### ISSUE TITLE
file input at html example doesnt contain psd file extension

### ISSUE THREAD

**Issue by ilsubyeega** [webtoon/psd#1]
https://user-images.githubusercontent.com/37479424/147951204-41ef0f15-4030-48fb-99f1-906f1c9b74bf.mp4

Currently the example accepts `image/vnd.adobe.photoshop,.psb`, however, this actually doesn't contain the .psd at the input dialog.
![image](https://user-images.githubusercontent.com/37479424/147951382-1a1deea1-3a3e-44bd-81a6-a5abbb6a9648.png)

**Comment by pastelmind** [comment]
Thanks for reporting this, and sorry about the delay!
