### ISSUE TITLE
Update Text in Layer

### ISSUE THREAD

**Issue by over12** [webtoon/psd#45]
its possible update a text in layer?
Example.. 
I have a layer with text "Hello World", I like the change to another text.

Its possible the make this using this lib?

Thanks.

**Comment by dlehdanakf** [comment]
Hello @over12 ,

I understood that changing another text meant that you wanted to save the replaced content as psd.
Only reading text information is supported.
You cannot save new information as a psd file.

Ultimately, we plan to offer that feature, but it's currently not possible.

Thankyou
