### ISSUE TITLE
ICC profile

### ISSUE THREAD

**Issue by scoiatael** [webtoon/psd#46]
One of features available in [psd-tools](https://github.com/psd-tools/psd-tools) is ICC profile handling. 

This is done by [extracting relevant tag](https://github.com/psd-tools/psd-tools/blob/4ff198368eebcda7c8bf385a3129e7481fbae8ab/src/psd_tools/psd/image_resources.py#L36) and then [converting image data after extraction](https://github.com/psd-tools/psd-tools/blob/f54b135e640785e76da6e6573c79241ec45bbdde/src/psd_tools/api/pil_io.py#L237).

This in turns uses Python bindings for `littlecms` (https://pypi.org/project/littlecms/). In our case this won't fly - closest thing I was able to find are [low-level binding based on emscripten](https://www.npmjs.com/package/js-lcms).

So the questions are:
- should this library handle the conversion or only expose information for ICC (and let users worry about converting themselves)? If former, is importing emscripten littlecms an ok solution? I'd rather create bindings ourselves than import npm library of dubious quality.
- can I start working on it? :) I suppose the first step would be to look into alternative libraries for conversion.

**Comment by pastelmind** [comment]
ICC color profiles are far beyond our interests--but if you can provide a PR, please go ahead! I can guarantee that no one (including myself) will be working on this for the foreseeable future.

That said, one of our goals is keeping the dependency count at zero. I also agree that having our own bindings would be better than importing another library. Either approach (full conversion VS simply exposing the raw data) is fine.

P. S. I am unfamiliar with ICC color profiles and color management. Could you briefly explain the value of this feature for me?

**Comment by scoiatael** [comment]
First of all - I'm also not an expert. What I know is that OpenDesign should support this feature: around 6% of designs on our platform (or, at least 6% of designs in sample I use for testing) have non-standard ICC profile: `adobeRGB` and `U.S. Web Coated (SWOP) v2` being the most common. 

For these designs exported images are wrong - colors are off (for some less, for others more). For some reason I can't get it to work with open-source version of `psd-tools`, so here's comparison from our internal fork: 
 
### exported from Photoshop:
![exported](https://user-images.githubusercontent.com/2892794/183434553-c1f9d129-288f-47e8-9e72-29300799fea8.png)


### `psd-tools` (internal):
![gitlab-psd-tools](https://user-images.githubusercontent.com/2892794/183434446-7db05076-4d7b-46d0-aa6d-0d00685cd527.png)


### `webtoon/psd`:

![webtoon](https://user-images.githubusercontent.com/2892794/183434676-021c4b84-b970-4098-8dfa-6285dc1dd69f.png)


---

Main reason that SWOP is so off is that it's the only CMYK color mode in this comparison.

Also looks like there is a proposal to have [colorSpace in ImageData](https://github.com/WICG/canvas-color-space/blob/main/CanvasColorSpaceProposal.md).

**Comment by scoiatael** [comment]
Did some testing and looks like minimal size added by color conversion via Little-CMS would be around ~400kB:
```
 384K ┌── lcms.js 
```

So it looks like the best course is to simply expose information on color profile and let users take care of conversion.
