### ISSUE TITLE
Proper instructions for contributions is needed

### ISSUE THREAD

**Issue by sifatul** [webtoon/psd#51]
Firstly guide on  how to install all the dependencies and run the project either in contribution.md or any other readme would help new contributors to onboard.

Secondly, guideline on what or how to contribute would be useful.

**Comment by pastelmind** [comment]
Hello! Thanks for reminding us. We're working on a Contribution Guide which includes instructions for setting up the development environment. Hopefully we'll publish it within a week!

**Comment by sifatul** [comment]
@pastelmind thanks for the reply. I am keen to work on this project. Would love to follow up on updates.
