### ISSUE TITLE
Regression: Additional Layer Info blocks are parsed incorrectly

### ISSUE THREAD

**Issue by pastelmind** [webtoon/psd#61]
Regression of bug that was fixed by f4fc9497d2826aeaed17910194dc9e8f7130ebe9, but re-emerged after merging #54.

Please see https://github.com/webtoon/psd/pull/54#discussion_r999429884 for details.

**Comment by scoiatael** [comment]
Oh, I see - sorry, but the comment arrived just after I hit merge and then I switched to other tasks.
Let me know if the proposed fix works on your private samples :) It works on mine.

We might want to work on a workflow where our sample files are used to verify PRs - although it'd be kinda hard to fully prevent leaking in a face of determined attacker, we could probably find some middle ground - like a private github runner which runs only on main.

**Comment by scoiatael** [comment]
Also another corollary - we might want to re-think nomenclature around AdditionalLayerInformation - I tried to follow your lead in code, and Adobe doesn't provide better naming sadly.
Looks like psd-tools also calls them tagged blocks consistently.
